version: '2'                                       
services:                                                          

  mysql:                                           
    image: mysql:5.7.12           
    ports:                                         
      - "3306:3306"                                
    volumes:                                       
      - ./.docker-volumes/mysql:/var/lib/mysql     
    environment:                                   
      - MYSQL_DATABASE=root                       
      - MYSQL_ROOT_PASSWORD=mypassword

  jupyter:
    image: jupyter/datascience-notebook
    ports:
     - "8888:8888"
    volumes:
     - /home/ubuntu/monkey_notebooks:/home/jovyan/work
     - /home/ubuntu/emoinvest/src/emoinvest/configurations:/home/jovyan/.jupyter
    environment:
     - JUPYTER_LAB_ENABLE=yes
