#!/usr/bin/env bash
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   ${DOCKER_RELEASE}"
apt-get update --allow-unauthenticated
apt-get install -y docker-ce mysql-client ${PYTHON_PKGS} python-virtualenv freetds-dev libssl-dev libffi-dev --allow-unauthenticated

curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /tmp/docker-compose
mv /tmp/docker-compose /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo sh -c "sudo usermod -a -G docker ${SUDO_USER}"
