#!/usr/bin/env bash                                
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -                          
sudo apt-key fingerprint 0EBFCD88                  
sudo add-apt-repository \                          
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \                                       
   $(lsb_release -cs) \                            
   stable"                                         
sudo apt-get update
sudo apt-get install -y docker-ce mysql-client python3.5 python3.5-dev python-virtualenv

curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /tmp/docker-compose                                                                               
sudo mv /tmp/docker-compose /usr/local/bin/docker-compose                                             
sudo chmod +x /usr/local/bin/docker-compose        
sudo sh -c 'useradd -G docker $SUDO_USER'          

